[package]
name = "synthetic-runtime"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
codec = { workspace = true }
pallet-synthetic = { path = "pallets/synthetic", default-features = false }
polkadot-sdk = { workspace = true, features = [
    "cumulus-primitives-core",
    "pallet-aura",
    "pallet-grandpa",
    "runtime",
    "pallet-balances",
    "pallet-sudo",
    "pallet-timestamp",
    "pallet-transaction-payment",
    "pallet-transaction-payment-rpc-runtime-api",
    "sp-consensus-aura",
    "sp-consensus-grandpa",
    "sp-keyring",
    "staging-parachain-info",
] }
scale-info = { workspace = true }
serde_json = { version = "1.0.145", default-features = false, features = ["alloc"] }

[build-dependencies]
polkadot-sdk = { workspace = true, features = ["substrate-wasm-builder"] }

[features]
default = ["std"]
std = [
    "codec/std",
    "pallet-synthetic/std",
    "polkadot-sdk/std",
    "scale-info/std",
    "serde_json/std",
]
